//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Combine



open class UsersAPI {

    public static let basePath = GutifyConstants.spotifyAPI

    /**
     Get Current User's Profile 
     - GET /me
     - Get detailed profile information about the current user (including the current user's username). 
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - returns: RequestBuilder<PrivateUserObjectDTO> 
     */
    open class func getCurrentUsersProfileWithRequestBuilder() -> RequestBuilder<PrivateUserObjectDTO> {
        let localVariablePath = "/me"
        let localVariableURLString = UsersAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PrivateUserObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
