//
// AuthorizationResponseDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AuthorizationResponseDTO: Codable, JSONEncodable, Hashable {

    /** to be used in PkceAccessTokenRequest */
    public var code: String
    /** the same as the state calculated by the client */
    public var state: String

    public init(code: String, state: String) {
        self.code = code
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(state, forKey: .state)
    }
}
