//
// TracksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Combine



open class MusicAPI {

    public static let basePath = GutifyConstants.spotifyAPI

    /**
     Get User's Top Tracks 
     - GET /me/top/tracks
     - Get the current user's top tracks based on calculated affinity. 
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter timeRange: (query)  (optional, default to "medium_term")
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PagingTrackObjectDTO> 
     */
    open class func getUsersTopTracksWithRequestBuilder(timeRange: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PagingTrackObjectDTO> {
        let localVariablePath = "/me/top/tracks"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "time_range": timeRange?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingTrackObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get User's Top Artists
     - GET /me/top/artists
     - Get the current user's top artists based on calculated affinity.
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter timeRange: (query)  (optional, default to "medium_term")
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PagingArtistObjectDTO>
     */
    open class func getUsersTopArtistsWithRequestBuilder(timeRange: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PagingArtistObjectDTO> {
        let localVariablePath = "/me/top/artists"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "time_range": timeRange?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingArtistObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
