//
// TracksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Combine



open class MusicAPI {

    public static let basePath = GutifyConstants.spotifyAPI

    /**
     Get User's Top Tracks 
     - GET /me/top/tracks
     - Get the current user's top tracks based on calculated affinity. 
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter timeRange: (query)  (optional, default to "medium_term")
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PagingTrackObjectDTO> 
     */
    open class func getUsersTopTracksWithRequestBuilder(timeRange: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PagingTrackObjectDTO> {
        let localVariablePath = "/me/top/tracks"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "time_range": timeRange?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingTrackObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get User's Top Artists
     - GET /me/top/artists
     - Get the current user's top artists based on calculated affinity.
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter timeRange: (query)  (optional, default to "medium_term")
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PagingArtistObjectDTO>
     */
    open class func getUsersTopArtistsWithRequestBuilder(timeRange: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PagingArtistObjectDTO> {
        let localVariablePath = "/me/top/artists"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "time_range": timeRange?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingArtistObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get New Releases
     - GET /browse/new-releases
     - Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<InlineResponse20010DTO>
     */
    open class func getNewReleasesWithRequestBuilder(limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<InlineResponse20010DTO> {
        let localVariablePath = "/browse/new-releases"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InlineResponse20010DTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get Current User's Playlists
     - GET /me/playlists
     - Get a list of the playlists owned or followed by the current Spotify user.
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PagingPlaylistObjectDTO>
     */
    open class func getAListOfCurrentUsersPlaylistsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PagingPlaylistObjectDTO> {
        let localVariablePath = "/me/playlists"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingPlaylistObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get User's Saved Albums
     - GET /me/albums
     - Get a list of the albums saved in the current Spotify user's 'Your Music' library.
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - parameter market: (query)  (optional)
     - returns: RequestBuilder<PagingSavedAlbumObjectDTO>
     */
    open class func getUsersSavedAlbumsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil, market: String? = nil) -> RequestBuilder<PagingSavedAlbumObjectDTO> {
        let localVariablePath = "/me/albums"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
            "market": market?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingSavedAlbumObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get User's Saved Tracks
     - GET /me/tracks
     - Get a list of the songs saved in the current Spotify user's 'Your Music' library.
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter market: (query)  (optional)
     - parameter limit: (query)  (optional, default to 20)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PagingSavedTrackObjectDTO>
     */
    open class func getUsersSavedTracksWithRequestBuilder(market: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PagingSavedTrackObjectDTO> {
        let localVariablePath = "/me/tracks"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "market": market?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "offset": offset?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagingSavedTrackObjectDTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
    
    /**
     Get Followed Artists
     - GET /me/following
     - Get the current user's followed artists.
     - OAuth:
       - type: oauth2
       - name: oauth_2_0
     - parameter type: (query)
     - parameter after: (query)  (optional)
     - parameter limit: (query)  (optional, default to 20)
     - returns: RequestBuilder<InlineResponse20011DTO>
     */
    open class func getFollowedWithRequestBuilder(after: String? = nil, limit: Int? = nil) -> RequestBuilder<InlineResponse20011DTO> {
        let localVariablePath = "/me/following"
        let localVariableURLString = MusicAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": "artist".encodeToJSON(),
            "after": after?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InlineResponse20011DTO>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
