//
// CursorPagingSimplifiedArtistObjectDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CursorPagingSimplifiedArtistObjectDTO: Codable, JSONEncodable, Hashable {

    /** A link to the Web API endpoint returning the full result of the request. */
    public var href: String?
    /** The maximum number of items in the response (as set in the query or by default). */
    public var limit: Int?
    /** URL to the next page of items. ( `null` if none) */
    public var next: String?
    /** The total number of items available to return. */
    public var total: Int?
    public var items: [ArtistObjectDTO]

    public init(href: String? = nil, limit: Int? = nil, next: String? = nil, total: Int? = nil, items: [ArtistObjectDTO]) {
        self.href = href
        self.limit = limit
        self.next = next
        self.total = total
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case href
        case limit
        case next
        case total
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(href, forKey: .href)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(next, forKey: .next)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encode(items, forKey: .items)
    }
}

