//
// FollowersObjectDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FollowersObjectDTO: Codable, JSONEncodable, Hashable {

    /** This will always be set to null, as the Web API does not support it at the moment.  */
    public var href: String?
    /** The total number of followers.  */
    public var total: Int?

    public init(href: String? = nil, total: Int? = nil) {
        self.href = href
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case href
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(href, forKey: .href)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

