//
// ImageObjectDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ImageObjectDTO: Codable, JSONEncodable, Hashable {

    /** The source URL of the image.  */
    public var url: String
    /** The image height in pixels.  */
    public var height: Int?
    /** The image width in pixels.  */
    public var width: Int?

    public init(url: String, height: Int?, width: Int?) {
        self.url = url
        self.height = height
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case height
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(height, forKey: .height)
        try container.encode(width, forKey: .width)
    }
}

