//
// InlineResponse20011DTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse20011DTO: Codable, JSONEncodable, Hashable {

    public var artists: CursorPagingSimplifiedArtistObjectDTO

    public init(artists: CursorPagingSimplifiedArtistObjectDTO) {
        self.artists = artists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artists
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artists, forKey: .artists)
    }
}

