//
// InlineResponse20010DTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InlineResponse20010DTO: Codable, JSONEncodable, Hashable {

    public var albums: PagingSimplifiedAlbumObjectDTO

    public init(albums: PagingSimplifiedAlbumObjectDTO) {
        self.albums = albums
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albums
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albums, forKey: .albums)
    }
}

