//
// SavedAlbumObjectDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SavedAlbumObjectDTO: Codable, JSONEncodable, Hashable {

    /** The date and time the album was saved Timestamps are returned in ISO 8601 format as Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is imprecise (for example, the date/time of an album release), an additional field indicates the precision; see for example, release_date in an album object.  */
    public var addedAt: Date?
    /** Information about the album. */
    public var album: AlbumObjectDTO

    public init(addedAt: Date? = nil, album: AlbumObjectDTO) {
        self.addedAt = addedAt
        self.album = album
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addedAt = "added_at"
        case album
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addedAt, forKey: .addedAt)
        try container.encode(album, forKey: .album)
    }
}

